services:
  - type: web
    name: helphive-community
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=75
